version: "3.9"
networks:
    docker_notebook_api:

services:
    nginx:
        image: nginx:stable-alpine
        container_name: docker_notebook_api_nginx
        ports:
            - "8081:80"
        volumes:
            - "./:/var/www/html"
            - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        networks:
            - docker_notebook_api

    mysql:
        image: mysql:8
        container_name: docker_notebook_api_mysql
        ports:
            - "5306:3306"
        volumes:
            - "./mysql:/var/lib/mysql"
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: docker_notebook_api
            #            MYSQL_USERNAME: root
            #            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_SERVICE_TAG: dev
            MYSQL_SERVICE_NAME: mysql
        networks:
            - docker_notebook_api

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: docker_notebook_api_php
        ports:
            - "9000:9000"
        volumes:
            - "./:/var/www/html"
        networks:
            - docker_notebook_api
